name: CD preprod

on:
  push:
    branches:
      - preprod

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Portainer webhook pull and redeploy
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{secrets.PORTAINER_WEBHOOK_SECRET}}
          method: POST
          preventFailureOnNoResponse: true